### ISSUE TITLE
eu868 channel initialization doesn't match arduino-lmic

### ISSUE THREAD

**Issue by terrillmoore** [terrillmoore/ibm-lmic#4]
The join code for eu868 seems to use 6 channels; the ardunio-lmic code uses three. Per @tftelkamp, these are not part of the eu868 channel plan for LoRaWAN 1.0.2, and were removed in advance based on prior knowledge. So we need to remove them here. Will file new issue.

**Comment by tftelkamp** [comment]
The 864.x channels are not part of the (just released) LoRaWAN 1.0.2 specification anymore. We anticipated this in arduino-lmic.

**Comment by terrillmoore** [comment]
OK. I will make the suitable adjustments. Thanks for your feedback. 

I also have a patch in both this repo and my Arduino-lmic repo that changes the constants 3 and 0x7 (which is (1 << 3) - 1) to MAX_DEFAULT_CHANNELS and (1 << MAX_DEFAULT_CHANNELS) - 1. I imagine that change will appear via the TTN-NY repo someday. And I imagine that this will help in supporting AS923 and other plans, which also ought to be published now.
